### ISSUE TITLE
Hey! :D

### ISSUE THREAD

**Issue by SoundeluXe87** [DoudouPike/portfolio#1]
:D

**Comment by DoudouPike** [comment]
Salut. =D
Tu vas bien ? Tu t'en sors avec le Portfolio ? ^^

**Comment by SoundeluXe87** [comment]
Coucou! :D
J'ai pas encore commencé, je taf déjà lol, mais je vais le faire avant la fin d'année, là je fais que de l'objet avec un framework qu'on n'a pas vu haha...
Et toi comment ça va?

**Comment by DoudouPike** [comment]
Ah ben tant mieux pour toi ! Ça fait des connaissances en plus, c'est cool.

Moi j'ai pas encore commencé la recherche de taf, et j'ai un peu de mal à bosser en autonomie sur mon portfolio. Les connaissances ça va, mais la motivation... Y'a tellement de distractions quand on est chez soi. ^^'
Mais bon, j'ai quand même bientôt fini mon portfolio. Je vais commencer la recherche de taf dans quelques jours.

Tu l'as trouvé sur internet ton job?

**Comment by SoundeluXe87** [comment]
Hello ^^
T'inquiètes je comprends, moi j'étais tellement en bad après la formation que j'ai même pas commencé le portfolio, fallait que je trouve du taf en bombe comme j'avais plus de droits avec pole emploi.

La je suis en train de bouffer de l'ajax au taf, c'est pas évident vu le contenu du cours sur ajax lol...

Oui j'ai trouvé sur le site de pole emploi. J'y suis allé au culot,

J'attends encore un moment avant de faire mon portfolio, pour le moment j'ai la race de taf comme dit...

J'ai pas regardé ce que ça donnait chez toi, tu as un lien ? :)

A bientôt!

**Comment by DoudouPike** [comment]
Moi c'était l'inverse : Après la formation j'étais content de pouvoir travailler sur un projet librement, d'avoir tout mon temps pour ça. Du coup au début je ne faisais que ça jour et nuit. ^^

Hmm ouais Ajax.. J'suis complètement à la ramasse avec ça. Va falloir que je me renseigne.

J'ai une adresse mais pour l'instant il n'est pas encore hébergé.
Voilà l'adresse : http://doudoupike.fr.
Si j'ai le temps je vais intégrer un système de notification par mail sur la page de maintenance.. comme ça, ceux qui se seront inscrits recevront une notification par mail quand le site sera en ligne.
Sinon je te tiendrai au courant. =)

Bon courage pour ton taf en tout cas ! C'est encourageant de se dire qu'on peut quand même postuler derrière !

A plus !

Le 16/11/2016 à 15:03, SoundeluXe87 a écrit :

Hello ^^
T'inquiètes je comprends, moi j'étais tellement en bad après la formation que j'ai même pas commencé le portfolio, fallait que je trouve du taf en bombe comme j'avais plus de droits avec pole emploi.

La je suis en train de bouffer de l'ajax au taf, c'est pas évident vu le contenu du cours sur ajax lol...

Oui j'ai trouvé sur le site de pole emploi. J'y suis allé au culot,

J'attends encore un moment avant de faire mon portfolio, pour le moment j'ai la race de taf comme dit...

J'ai pas regardé ce que ça donnait chez toi, tu as un lien ? :)

A bientôt!

**Comment by DoudouPike** [comment]
Yo !
Voilà, Portfolio terminé ! Il n'est pas encore complété au maximum, mais c'est déjà ça !
Il est ici : https://doudoupike.fr.

J'ai quelques soucis avec l'indexation par Google. Mais sinon tout est nickel.
Je l'envoi aujourd'hui à Alex et Pascal pour qu'ils y jettent un œil avant que je le soumette à la validation.

Ça va toi le taf ?

**Comment by SoundeluXe87** [comment]
Heeey, merci beaucoup, je regarderai ça!!! :D

**Comment by SoundeluXe87** [comment]
Hey doudoupike! :)
Ca va depuis le temps?

**Comment by DoudouPike** [comment]
J'viens de voir que j'ai complètement raté ton message.
2 mois de retard... :+1: 

Moi ça va super ! Je bosse en tant que dev dans une entreprise qui fait du telecom à côté de Strasbourg depuis le mois de mai. En 4 mois de boulot j'ai appris beaucoup de nouvelles choses. La 3WA ne m'aura pas servi à rien, j'ai pu me réorienté professionnellement après seulement 3 mois de formation, c'est quand même super cool.

Et toi ça va ? Tu bosses toujours dans la même boite ?

**Comment by DoudouPike** [comment]
Ah et moi aussi j'ai dû bouffer de l'AJAX dès le début ici. Mais pas avec jQuery, on utilise Dojo ici. Du coup au début c'était bien dur. =')
