### ISSUE TITLE
Remove SQL dumps with personal information

### ISSUE THREAD

**Issue by TimboKZ** [DoudouPike/portfolio#2]
You're exposing personal information in your SQL dump:

https://github.com/DoudouPike/portfolio/blob/master/portfolio.sql#L171-L176

**Comment by DoudouPike** [comment]
It's fix! Thanks!

**Comment by TimboKZ** [comment]
No worries. Keep in mind that the data will still appear in the commit message ( https://github.com/DoudouPike/portfolio/commit/f73bb5934b71e14b140de258acfaa388732cba87 ) - you might need to follow these instructions to completely erase it:

https://help.github.com/articles/removing-sensitive-data-from-a-repository/
